name: test
version: '${project.version}'
main: at.floticey.waypoints.Waypoints
api-version: '1.20'
commands:
  waypoint:
    create:
        description: Create a waypoint
        usage: create <name>
    edit:
        description: Edit a waypoint
        usage: edit <name>
    delete:
        description: Delete a waypoint
        usage: delete <name>
  waypoints:
